# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: autoflake
        name: Remove unused variables and imports
        entry: bash -c 'autoflake "$@";' --
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports"
          ]
        files: \.py$
      - id: isort
        name: Sorting import statements
        entry: bash -c 'isort "$@";'
        language: python
        args: [ "--filter-files" ]
        files: \.py$
      - id: black
        name: Black Python code formatting
        exclude: ^templates/
        entry: bash -c 'black "$@";'
        language: python
        types: [python]
        args: [ "--line-length=88" ]
