version: '3.8'

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8050:8000"
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.2
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jusan_user
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=jusan_dev

volumes:
  pg_data:
