# Generated by Django 3.2.12 on 2022-12-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='avatar',
        ),
    ]
