# Generated by Django 3.2.12 on 2022-12-28 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credit_cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего изменения"
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Сумма")),
                ("commission", models.FloatField(default=0, verbose_name="Комиссия")),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="Метаданные"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "TRANSFER"),
                            ("TRANSFER_TO_OTHER_BANK", "TRANSFER_TO_OTHER_BANK"),
                            ("PAYOUT", "PAYOUT"),
                            ("PURCHASE", "PURCHASE"),
                        ],
                        max_length=50,
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "destination_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transactions",
                        to="credit_cards.creditcard",
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "source_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transactions",
                        to="credit_cards.creditcard",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
    ]
