# Generated by Django 3.2.12 on 2022-12-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TRANSFER', 'TRANSFER'), ('TRANSFER_TO_OTHER_BANK', 'TRANSFER_TO_OTHER_BANK'), ('PAYOUT', 'PAYOUT')], max_length=50, verbose_name='Тип транзакции'),
        ),
    ]
