# Generated by Django 3.2.12 on 2022-12-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Фото'),
        ),
    ]
