# Generated by Django 3.2.12 on 2022-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221227_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
