# Generated by Django 3.2.12 on 2022-12-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug-category', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
